### ISSUE TITLE
Converted primenet.py to binary with Nuitka

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#108]
Nuitka is a python compiler written in python. I have converted primenet.py to a binary program.
It shows exact behavior like the py version.
Option to make a standalone binary that does not require a python installation is also available.

http://nuitka.net/

**Comment by preda** [comment]
Thank you, but personally I would prefer to run a python script (that I can read and edit if needed) than a binary. I understand that the main advantage of the binary is that one does not need a python installation (or something else?). But python install is pretty standard, at least on Linux, nowadays.

As an example, I appreaciate that rocm-smi is a python script rather than an opaque binary.

**Comment by valeriob01** [comment]
> Thank you, but personally I prefer to run a python script (that I can read and edit if needed) than a binary. I suppose the main advantage of the binary is that one does not need a python installation (or something else?). But python install is pretty standard, at least on Linux, nowadays.
> 
> As an example, I appreaciate that rocm-smi is a python script rather than an opaque binary.

I did that to test the speed of compiled python, they give it at 312%.

**Comment by valeriob01** [comment]
PS: Obviously that make sense only once the python script is fully debugged.

**Comment by valeriob01** [comment]
There was this idea for a long time that Python was just for glue code, but people are obviously writing real stuff in it. An aggressive runtime seems overdue.

**Comment by preda** [comment]
Valerio, IMO that script is doing so little work that its performance is a no-issue.

**Comment by valeriob01** [comment]
> Valerio, IMO that script is doing so little work that its performance is a no-issue.

True, but still it is measurable with a difference :-)
