### ISSUE TITLE
filesystem: no such file or directory

### ISSUE THREAD

**Issue by Danc2050** [preda/gpuowl#115]
> In file included from Worktodo.cpp:6:0:
> File.h:10:10: fatal error: filesystem: No such file or directory
>  #include <filesystem>

I have not changed the folder in any way and just ran `make` as directed. Any help?

**Comment by preda** [comment]
probably you need a more recent version of the compiler. What version are you using?
g++ --version

**Comment by Danc2050** [comment]
`g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`

**Comment by preda** [comment]
https://stackoverflow.com/questions/45867379/why-does-gcc-not-seem-to-have-the-filesystem-standard-library

Probably gcc 8 (or later) should be fine.

**Comment by joshuahonig** [comment]
Sorry to revive a dead thread. I'm having this same issue, and have installed gcc 8, which hasn't fixed the issue. I'm very new to compiling programs so there's a good chance I'm doing something wrong. Here's the output of `make`:
```
echo \"`git describe --long --dirty --always`\" > version.new
diff -q -N version.new version.inc >/dev/null || mv version.new version.inc
echo Version: `cat version.inc`
Version: "v6.11-211-gca63aa9"
g++ -MT Worktodo.o -MMD -MP -MF .d/Worktodo.Td -Wall -O2 -std=c++17   -c -o Worktodo.o Worktodo.cpp
In file included from Worktodo.cpp:6:0:
File.h:10:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
Makefile:30: recipe for target 'Worktodo.o' failed
make: *** [Worktodo.o] Error 1
```

I'm running Ubuntu 18.04.4.

**Comment by joshuahonig** [comment]
I spoke too soon. My guess is that `make` was defaulting to gcc 7. The following code switched it to gcc 8 and I got a successful compilation: 
```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 8
```

**Comment by wedgingt** [comment]
gcc v8 is not yet available for Ubuntu Linux 18.04 nor Cygwin.
Is there an alternative?

**Comment by preda** [comment]
@wedgingt did you do a search: https://askubuntu.com/questions/1028601/install-gcc-8-only-on-ubuntu-18-04
The alternative is ubuntu 20.04 (LTS).

**Comment by wedgingt** [comment]
Yes, I saw that - admittedly, after I posted the prior message, when I realized you had to have gcc v8 somewhere and Ubuntu tends to get new gcc fairly quickly.
But Ubuntu 20.04 has only been out since April, so I doubt a lot of people have upgraded yet.
In any case, I can't upgrade until some long running processes complete, which will likely be another week, perhaps longer.

For Cygwin, it seems I had not updated that in a while; it now has gcc v9.  After that and installing python3, I only had to
and an #ifdef __CYGWIN__ to use sleep() rather than usleep() in Queue.h and it builds; I'll commit to my fork of gpuowl
presently and send you a pull request for you to look over.
