### ISSUE TITLE
Will gpuOwl be converted to OpenCL 3.0 ?

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#191]
Announcement from Khronos today: https://www.khronos.org/blog/opencl-3.0-specification-finalized-and-initial-khronos-open-source-opencl-sdk-released

**Comment by baryluk** [comment]
What for exactly?

**Comment by valeriob01** [comment]
evolution ?

**Comment by preda** [comment]
I don't see an important benefit ATM. Also AFAIK there are now implementations on AMD hardware, so that's that.

As I understand it, OpenCL 3.0 does not add things, it mainly makes the various parts optional/configurable.

**Comment by baryluk** [comment]
Yes, I think the same. There is nothing interesting in OpenCL 3.0 really. It might be good for new project, but there is nothing wrong sticking to OpenCL 2.x indefinitively. Porting to OpenCL 3.x should be hard, but as you said, there are no implementations, so that would make it less accessible. OpenCL 3.x will probably get some interesting features in the future, so then things can be re-evaluated.

**Comment by valeriob01** [comment]
Maybe you both should read the full announcement: OpenCL 3.0 brings C plus plus for OpenCL to write kernels directly. And, 
Some of the longer-term design directions being considered by the OpenCL Working Group are:
    Recordable Command buffers
    Machine Learning Primitives
    Indirect Dispatch
    Device Topology
    Unified Shared Memory
    Global Barriers

Notably the Device Topology feature can help you implement the long missing feature of correctly detecting the GPU UUID.

ATM I have to apply a patch to correctly detect my GPU UUIDs which makes the gpuOwl version dirty.

**Comment by valeriob01** [comment]
and btw, I was talking "will be" that refers to the future, mind how you read what I write.
