### ISSUE TITLE
Exception 9: gpu_error INVALID_VALUE

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#51]
https://github.com/preda/gpuowl/blob/ea4953e5575dffedf04be0764fa70e40aa0bd8b0/clwrap.cpp#L193

**Comment by valeriob01** [comment]
By copying the old gpuowl-wrap.cl and recompiling it works.

**Comment by preda** [comment]
Can you try this: remove gpuowl-wrap.cl, re-build, then look at gpuowl-wrap.cl (which is generated based on gpuowl.cl) and see what it looks like. Maybe a build problem with gpuowl-wrap.cl not being generated correctly.

**Comment by valeriob01** [comment]
Done. gpuowl-wrap.cl starts with:

R"clsource(

I can send you the file if you need it.

**Comment by sillygitter** [comment]
I have what could be a similar issue.

`Exception 9gpu_error:  clGetPlatformIDs(16, platforms, (unsigned *) &nPlatforms) at clwrap.cpp:72 getDeviceIDs`

Corresponding to

`  CHECK1(clGetPlatformIDs(16, platforms, (unsigned *) &nPlatforms));`

Trying to compile with g++-8 for now as I don't have and cannot easily download g++-9.

**Comment by valeriob01** [comment]
g++-9 was easy to install on ubuntu. On debian buster I had to enable both buster and experimental repositories, then:

apt -t experimental install g++-9

**Comment by preda** [comment]
Any g++ version should be fine, g++-9 is not required; feel free to change to g++ or something else. 

But this does not explain the exception. There is an exception on clGetPlatformIDs(). Did it work before? does an old version still work? is the OpenCL setup working (e.g. clinfo)

**Comment by valeriob01** [comment]
> Any g++ version should be fine, g++-9 is not required; feel free to change to g++ or something else.
> 
> But this does not explain the exception. There is an exception on clGetPlatformIDs(). Did it work before? does an old version still work? is the OpenCL setup working (e.g. clinfo)

His issue sounds more severe than mine. Happens on CHECK1, mine on CHECK2.

**Comment by sillygitter** [comment]
Ah, something's gone belly up with my OpenCL install. Worked fine a few hours ago before a reboot but now older versions and clinfo no longer work either, strange as all I've done since is reboot and try to compile the latest version. Now updating everything while keeping rocm at 2.2 and will see where it stands later.

The g++-9 problem is nothing to do with g++ and everything to do with my slow and spotty mobile connection, makes updating anything over a few dozen megabytes a bit of a mission.
