### ISSUE TITLE
PM1 success result incorrect

### ISSUE THREAD

**Issue by mrh42** [preda/gpuowl#87]
When gpuowl PM1 finds a factor, 2^n-1 is printed instead of the factor.  A lot of digits!  Try -pm1 95531 and notice it tries to print 28k digits.  I think the problem is with one of the calls to writeResultPM1() in Task.cc, but I don't see the fix.

**Comment by preda** [comment]
Thanks for the report, investigating.

**Comment by preda** [comment]
It seems what happened is that the data read from the GPU ("words") was all-zero, and that in one of the inputs in GCD(2^n -1, words) which evaluates to 2^n - 1. This is only supposed to happen on GPU errors. P-1 (both stages) are not protected against errors in the way PRP is -- P-1 is vulnerable. If you suspect errors on the GPU, you should do a few days of PRP, and only when that is rock-solid (not any  errors at all) switch to P-1 on this verified setup.

I added a throw instead of printing invalid huge factors.

**Comment by mrh42** [comment]
Hmm.  My VII has been running rock solid at setsclk 3 for months of PRP.  Behaves the same way if I use my 1070ti as well.  Does this work for others: 

 ./gpuowl -device 0 -pm1 95531 -B1 5000 -B2 10000 -maxAlloc 4096 -yield

only takes a few seconds to run.

**Comment by mrh42** [comment]
Never mind, I pulled the latest from git and it works fine.  I was a few weeks behind.
